# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

const_c <- function(sigw, sigv) {
    .Call('_covarianceBP_const_c', PACKAGE = 'covarianceBP', sigw, sigv)
}

#' mvrnormArma
#'
#' This function returns n samples of multivariate normal distribution with
#' mean mu and variance Sigma.
#'
#' @param n Sample size
#' @param mu Mean vector
#' @param Sigma Variance-covariance matrix
#' @export
mvrnormArma <- function(n, mu, Sigma) {
    .Call('_covarianceBP_mvrnormArma', PACKAGE = 'covarianceBP', n, mu, Sigma)
}

