# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

const_c <- function(sigw, sigv) {
    .Call('_DynamicCorrelation_const_c', PACKAGE = 'DynamicCorrelation', sigw, sigv)
}

#' mvrnormArma
#'
#' This function returns n samples of multivariate normal distribution with
#' mean mu and variance Sigma.
#'
#' @param n Sample size
#' @param mu Mean vector
#' @param Sigma Variance-covariance matrix
#' @export
mvrnormArma <- function(n, mu, Sigma) {
    .Call('_DynamicCorrelation_mvrnormArma', PACKAGE = 'DynamicCorrelation', n, mu, Sigma)
}

#' @export
get_A1_c <- function(k, p, TT, RR, n) {
    .Call('_DynamicCorrelation_get_A1_c', PACKAGE = 'DynamicCorrelation', k, p, TT, RR, n)
}

#' @export
get_A2_c <- function(k, p, TT, RR, n) {
    .Call('_DynamicCorrelation_get_A2_c', PACKAGE = 'DynamicCorrelation', k, p, TT, RR, n)
}

#' @export
get_A3_c <- function(k, p, TT, RR, n) {
    .Call('_DynamicCorrelation_get_A3_c', PACKAGE = 'DynamicCorrelation', k, p, TT, RR, n)
}

#' @export
get_TT_RR_c <- function(A) {
    .Call('_DynamicCorrelation_get_TT_RR_c', PACKAGE = 'DynamicCorrelation', A)
}

#' @export
cubic_coeff <- function(x) {
    .Call('_DynamicCorrelation_cubic_coeff', PACKAGE = 'DynamicCorrelation', x)
}

#' @export
shuffle_x_c <- function(x, B) {
    .Call('_DynamicCorrelation_shuffle_x_c', PACKAGE = 'DynamicCorrelation', x, B)
}

#' @export
store_W_c <- function(y, smallY) {
    .Call('_DynamicCorrelation_store_W_c', PACKAGE = 'DynamicCorrelation', y, smallY)
}

#' @export
store_V_c <- function(y, smallY) {
    .Call('_DynamicCorrelation_store_V_c', PACKAGE = 'DynamicCorrelation', y, smallY)
}

